repositories:
  - name: stable
    url: http://storage.googleapis.com/kubernetes-charts
  - name: incubator
    url: http://storage.googleapis.com/kubernetes-charts-incubator

helmDefaults:
  tillerNamespace: bsapi-prod

releases:
  - name: bsapi-message-ids
    namespace: bsapi-prod
    chart: stable/redis
    version: 5.1.3
    values:
      - values.yaml
